# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solve Modified Estimation Equation using Quasi-Newton Algorithm
#'
#' This is a function to implement Quasi-Newton Algorithm to solve modified estimation equations.
#'
#'
#' @param freq_table frequency table
#' @param X Design matrix of all samples
#' @param beta_init Initial value of beta parameters
#' @param weight weight in the estimation equations
#' @param tol Stopping criterion. Default value is 1e-6.
#' @param iter_max Maximum iteration number
NULL

CalculateXX <- function(X) {
    .Call(`_LOCOM_CalculateXX`, X)
}

#' @examples
#' between(1:12, 7, 9)
#'
Newton <- function(freq_table, X, XX, beta_init, weight, tol, iter_max, Firth_thresh, prop_presence) {
    .Call(`_LOCOM_Newton`, freq_table, X, XX, beta_init, weight, tol, iter_max, Firth_thresh, prop_presence)
}

perm_Newton <- function(freq_table, Yr, X, XX, beta_init, weight, perm, tol, iter_max, Firth_thresh, prop_presence) {
    .Call(`_LOCOM_perm_Newton`, freq_table, Yr, X, XX, beta_init, weight, perm, tol, iter_max, Firth_thresh, prop_presence)
}

